--- #YAML:1.0
name:               Business-OnlinePayment
version:            3.02
abstract:           ~
author:
    - Ivan Kohler <ivan-business-onlinepayment@420.am>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::HTTPS::Any:  0
    Tie::IxHash:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
