# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-OnlinePayment
version:      3.00
version_from: OnlinePayment.pm
installdirs:  site
requires:
    URI::Escape:                   0
    Tie::IxHash:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
