---
abstract: unknown
author:
  - 'Ivan Kohler <ivan-business-onlinepayment@420.am>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-OnlinePayment
no_index:
  directory:
    - t
    - inc
requires:
  Net::HTTPS::Any: 0
  Tie::IxHash: 0
version: 3.03
